# Generated by Django 5.0 on 2023-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.PositiveIntegerField(verbose_name='user_id')),
                ('timestamp', models.DateField(auto_now_add=True, null=True, verbose_name='timestamp')),
                ('message_body', models.CharField(max_length=150, null=True, verbose_name='message_body')),
            ],
        ),
    ]
